### ISSUE TITLE
登陆提示 登陆异常 

### ISSUE THREAD

**Issue by liuyouth** [scorego/WechatRobot#2]
`java.lang.StringIndexOutOfBoundsException: String index out of range: -7
	at java.lang.String.substring(String.java:1967)
	at me.xuxiaoxiao.chatapi.wechat.WeChatApi.webwxnewloginpage(WeChatApi.java:108)
	at me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread.login(WeChatClient.java:729)
	at me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread.run(WeChatClient.java:679)
2019-07-09 09:21:15.033 | W | Thread-0 | chatapi-wechat | 登录异常
String index out of range: -7`

**Comment by scorego** [comment]
现在还有这个问题吗

**Comment by liuyouth** [comment]
我明天在运行看看，多谢这么晚回答我的问题


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Javior Wang <notifications@github.com>
发送时间: 2019年7月10日 22:52
收件人: scorego/WechatRobot <WechatRobot@noreply.github.com>
抄送: 小白 <869689491@qq.com>, Author <author@noreply.github.com>
主题: 回复：[scorego/WechatRobot] 登陆提示 登陆异常  (#2)




现在还有这个问题吗

**Comment by liuyouth** [comment]
这是今天下午登陆的 手机会弹出登陆网页版 然后我点击确定就这样了 






------------------ 原始邮件 ------------------
发件人: "Javior Wang"<notifications@github.com>; 
发送时间: 2019年7月10日(星期三) 晚上10:52
收件人: "scorego/WechatRobot"<WechatRobot@noreply.github.com>; 
抄送: "刘博"<869689491@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [scorego/WechatRobot] 登陆提示 登陆异常  (#2)




现在还有这个问题吗

**Comment by liuyouth** [comment]
> 现在还有这个问题吗

还有的

**Comment by scorego** [comment]
你确定一下你的微信能登陆网页版微信吗？
https://wx.qq.com/

**Comment by liuyouth** [comment]
两个号都是这样的提示




------------------ 原始邮件 ------------------
发件人: "Javior Wang"<notifications@github.com>; 
发送时间: 2019年7月11日(星期四) 晚上7:47
收件人: "scorego/WechatRobot"<WechatRobot@noreply.github.com>; 
抄送: "刘博"<869689491@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [scorego/WechatRobot] 登陆提示 登陆异常  (#2)




你确定一下你的微信能登陆网页版微信吗？
 https://wx.qq.com/

**Comment by scorego** [comment]
我的意思是确认一下号能不能登网页版微信。因为近几年新注册的微信号都是没有网页版微信的权限的。如果确定能登录，那么需要进一步排查。

**Comment by scorego** [comment]
@xuxiaoxiao-xxx 然后就是要请一下ChatApi-WeChat的作者来看一下

**Comment by liuyouth** [comment]
> @ xuxiaoxiao-XXX然后就是要请一下ChatApi，微信的作者来看一下

我微信算是老号了之前可以登陆 后来没试过 ，今天不行
然后是不是这个接口就要封了 ，得用 ipad 协议了

**Comment by scorego** [comment]
网页微信封不封目前不清楚，网页QQ早就停用了，而且新注册的微信号都不能使用网页微信了，所以网页微信前途不明朗。但是如果确定能登录网页微信的号还是可以正常使用的。

**Comment by liuyouth** [comment]
> 网页微信封不封目前不清楚，网页QQ早就停用了，而且新注册的微信号都不能使用网页微信了，所以网页微信前途不明朗。但是如果确定能登录网页微信的号还是可以正常使用的。

好的，我再找找类似应用吧😜

**Comment by xuxiaoxiao-xxx** [comment]
看了一下错误信息，是登录后获取uin时出错了，uin是空的。看来这块还要加上非空判断才行
